dependencies:
  - name: auth
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ymesika/refarch-cloudnative-kubernetes/master/docs/charts
  - name: catalog
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: customer
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: inventory
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: orders
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: web
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: ibmcase-couchdb
    version: 0.2.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: ibmcase-inventory-mysql
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: ibmcase-orders-mysql
    version: 0.3.1
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
  - name: ibmcase-elasticsearch
    version: 0.2.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
